using System;
using System.Linq;
using System.Threading.Tasks;
using Dapper;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Data.SqlClient;
using IronDev.Core.Interfaces;
using IronDev.Data.Models;
using IronDev.Services;

namespace IronDev.IntegrationTests;

[TestClass]
public class TicketServiceIntegrationTests : IntegrationTestBase
{
    [TestMethod]
    public async Task SaveTicketAsync_And_GetRecentTicketsAsync_ShouldReturnSavedTicket()
    {
        using var scope = ServiceProvider.CreateScope();
        var ticketService = scope.ServiceProvider.GetRequiredService<ITicketService>();

        var projectId = await SeedProjectAsync();
        var sessionId = Guid.NewGuid();

        var ticketId = await ticketService.SaveTicketAsync(new ProjectTicket
        {
            ProjectId = projectId,
            SessionId = sessionId,
            Title = "Add persistence test for UI save behavior",
            TicketType = "Task",
            Priority = "Medium",
            Status = "Draft",
            Summary = "Create a UI-focused test for save flow.",
            Background = "Need confidence in save behavior.",
            Problem = "No integration coverage exists.",
            AcceptanceCriteria = "- Save persists data correctly",
            Content = "Fallback content",
            TechnicalNotes = ""
        });

        var tickets = await ticketService.GetRecentTicketsAsync(projectId, 10);
        var loaded = await ticketService.GetTicketByIdAsync(ticketId);

        Assert.IsNotNull(loaded);
        Assert.IsTrue(ticketId > 0);
        Assert.HasCount(1, tickets);
        Assert.AreEqual("Add persistence test for UI save behavior", loaded.Title);
        Assert.AreEqual("Task", loaded.TicketType);
        Assert.AreEqual("Draft", loaded.Status);
    }
    [TestMethod]
    public async Task SaveTicketAsync_WithExtendedFields_ShouldPersistAllFields()
    {
        using var scope = ServiceProvider.CreateScope();
        var ticketService = scope.ServiceProvider.GetRequiredService<ITicketService>();

        var projectId = await SeedProjectAsync();
        var sessionId = Guid.NewGuid();

        var ticket = new ProjectTicket
        {
            ProjectId = projectId,
            SessionId = sessionId,
            Title = "Full Draft Persistence Test",
            TicketType = "Feature",
            Priority = "High",
            Status = "Draft",
            Summary = "Test all new columns.",
            Background = "Verify schema updates.",
            Problem = "Persistence risk for new fields.",
            AcceptanceCriteria = "All fields reload correctly.",
            Content = "Test content",
            LinkedFilePaths = "FileA.cs;FileB.cs",
            LinkedSymbols = "ClassA;MethodB",
            UnitTests = "Unit Test Content",
            IntegrationTests = "Integration Test Content",
            ManualTests = "Manual Test Content",
            RegressionTests = "Regression Test Content",
            BuildValidation = "dotnet test",
            ContextSummary = "AI Context Summary",
            IsGenerated = true,
            GenerationNote = "Generated by AI model X",
            SourceChatSessionId = 1001,
            SourceChatMessageId = 2002
        };

        var ticketId = await ticketService.SaveTicketAsync(ticket);
        var loaded = await ticketService.GetTicketByIdAsync(ticketId);

        Assert.IsNotNull(loaded);
        Assert.AreEqual(ticket.Title, loaded.Title);
        Assert.AreEqual(ticket.TicketType, loaded.TicketType);
        Assert.AreEqual(ticket.Priority, loaded.Priority);
        Assert.AreEqual(ticket.Summary, loaded.Summary);
        Assert.AreEqual(ticket.Background, loaded.Background);
        Assert.AreEqual(ticket.Problem, loaded.Problem);
        Assert.AreEqual(ticket.AcceptanceCriteria, loaded.AcceptanceCriteria);
        Assert.AreEqual(ticket.LinkedFilePaths, loaded.LinkedFilePaths);
        Assert.AreEqual(ticket.LinkedSymbols, loaded.LinkedSymbols);
        Assert.AreEqual(ticket.UnitTests, loaded.UnitTests);
        Assert.AreEqual(ticket.IntegrationTests, loaded.IntegrationTests);
        Assert.AreEqual(ticket.ManualTests, loaded.ManualTests);
        Assert.AreEqual(ticket.RegressionTests, loaded.RegressionTests);
        Assert.AreEqual(ticket.BuildValidation, loaded.BuildValidation);
        Assert.AreEqual(ticket.ContextSummary, loaded.ContextSummary);
        Assert.AreEqual(ticket.IsGenerated, loaded.IsGenerated);
        Assert.AreEqual(ticket.GenerationNote, loaded.GenerationNote);
        Assert.AreEqual(ticket.SourceChatSessionId, loaded.SourceChatSessionId);
        Assert.AreEqual(ticket.SourceChatMessageId, loaded.SourceChatMessageId);
    }

    [TestMethod]
    public async Task SaveTicketAsync_WithSourceContext_ShouldRecordArtifactReferences()
    {
        using var scope = ServiceProvider.CreateScope();
        var ticketService = scope.ServiceProvider.GetRequiredService<ITicketService>();
        var referenceService = scope.ServiceProvider.GetRequiredService<IArtifactSourceReferenceService>();

        var projectId = await SeedProjectAsync();

        var ticketId = await ticketService.SaveTicketAsync(new ProjectTicket
        {
            ProjectId = projectId,
            SessionId = Guid.NewGuid(),
            Title = "Trace ticket source",
            TicketType = "Task",
            Priority = "Medium",
            Status = "Draft",
            Content = "Traceability test",
            SourceChatSessionId = 3003,
            SourceChatMessageId = 4004
        });

        var references = await referenceService.GetForArtifactAsync(
            tenantId: 1,
            projectId: projectId,
            artifactType: "Ticket",
            artifactId: ticketId);

        Assert.HasCount(2, references);
        Assert.IsTrue(references.Any(r =>
            r.SourceType == "ChatSession" &&
            r.SourceId == 3003 &&
            r.ReferenceType == "CreatedFrom"));
        Assert.IsTrue(references.Any(r =>
            r.SourceType == "ChatMessage" &&
            r.SourceId == 4004 &&
            r.ReferenceType == "CreatedFrom"));
    }

    [TestMethod]
    public async Task TicketTraceability_WithLegacySchema_ShouldSelfHealColumnsAndReferenceTable()
    {
        var projectId = await SeedProjectAsync();

        await using (var connection = new SqlConnection(ConnectionString))
        {
            await connection.OpenAsync();
            await connection.ExecuteAsync("""
                IF OBJECT_ID('dbo.ArtifactSourceReferences', 'U') IS NOT NULL
                    DROP TABLE dbo.ArtifactSourceReferences;

                IF COL_LENGTH('dbo.ProjectTickets', 'SourceChatSessionId') IS NOT NULL
                    ALTER TABLE dbo.ProjectTickets DROP COLUMN SourceChatSessionId;

                IF COL_LENGTH('dbo.ProjectTickets', 'SourceChatMessageId') IS NOT NULL
                    ALTER TABLE dbo.ProjectTickets DROP COLUMN SourceChatMessageId;
                """);
        }

        using var scope = ServiceProvider.CreateScope();
        var ticketService = scope.ServiceProvider.GetRequiredService<ITicketService>();
        var referenceService = scope.ServiceProvider.GetRequiredService<IArtifactSourceReferenceService>();

        var ticketId = await ticketService.SaveTicketAsync(new ProjectTicket
        {
            ProjectId = projectId,
            SessionId = Guid.NewGuid(),
            Title = "Legacy schema traceability",
            TicketType = "Task",
            Priority = "Medium",
            Status = "Draft",
            Content = "Legacy schema self-heal test",
            SourceChatSessionId = 9009,
            SourceChatMessageId = 9010
        });

        var loaded = await ticketService.GetTicketByIdAsync(ticketId);
        var references = await referenceService.GetForArtifactAsync(1, projectId, "Ticket", ticketId);

        Assert.IsNotNull(loaded);
        Assert.AreEqual(9009, loaded.SourceChatSessionId);
        Assert.AreEqual(9010, loaded.SourceChatMessageId);
        Assert.HasCount(2, references);
    }
}
