using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using IronDev.Data.Models;
using IronDev.Services;

namespace IronDev.IntegrationTests;

[TestClass]
public class TicketServiceIntegrationTests : IntegrationTestBase
{
    [TestMethod]
    public async Task SaveTicketAsync_And_GetRecentTicketsAsync_ShouldReturnSavedTicket()
    {
        using var scope = ServiceProvider.CreateScope();
        var ticketService = scope.ServiceProvider.GetRequiredService<ITicketService>();

        var projectId = await SeedProjectAsync();
        var sessionId = Guid.NewGuid();

        var ticketId = await ticketService.SaveTicketAsync(new ProjectTicket
        {
            ProjectId = projectId,
            SessionId = sessionId,
            Title = "Add persistence test for UI save behavior",
            TicketType = "Task",
            Priority = "Medium",
            Status = "Draft",
            Summary = "Create a UI-focused test for save flow.",
            Background = "Need confidence in save behavior.",
            Problem = "No integration coverage exists.",
            AcceptanceCriteria = "- Save persists data correctly",
            Content = "Fallback content",
            TechnicalNotes = ""
        });

        var tickets = await ticketService.GetRecentTicketsAsync(projectId, 10);
        var loaded = await ticketService.GetTicketByIdAsync(ticketId);

        Assert.IsNotNull(loaded);
        Assert.IsTrue(ticketId > 0);
        Assert.HasCount(1, tickets);
        Assert.AreEqual("Add persistence test for UI save behavior", loaded.Title);
        Assert.AreEqual("Task", loaded.TicketType);
        Assert.AreEqual("Draft", loaded.Status);
    }
    [TestMethod]
    public async Task SaveTicketAsync_WithExtendedFields_ShouldPersistAllFields()
    {
        using var scope = ServiceProvider.CreateScope();
        var ticketService = scope.ServiceProvider.GetRequiredService<ITicketService>();

        var projectId = await SeedProjectAsync();
        var sessionId = Guid.NewGuid();

        var ticket = new ProjectTicket
        {
            ProjectId = projectId,
            SessionId = sessionId,
            Title = "Full Draft Persistence Test",
            TicketType = "Feature",
            Priority = "High",
            Status = "Draft",
            Summary = "Test all new columns.",
            Background = "Verify schema updates.",
            Problem = "Persistence risk for new fields.",
            AcceptanceCriteria = "All fields reload correctly.",
            Content = "Test content",
            LinkedFilePaths = "FileA.cs;FileB.cs",
            LinkedSymbols = "ClassA;MethodB",
            UnitTests = "Unit Test Content",
            IntegrationTests = "Integration Test Content",
            ManualTests = "Manual Test Content",
            RegressionTests = "Regression Test Content",
            BuildValidation = "dotnet test",
            ContextSummary = "AI Context Summary",
            IsGenerated = true,
            GenerationNote = "Generated by AI model X"
        };

        var ticketId = await ticketService.SaveTicketAsync(ticket);
        var loaded = await ticketService.GetTicketByIdAsync(ticketId);

        Assert.IsNotNull(loaded);
        Assert.AreEqual(ticket.Title, loaded.Title);
        Assert.AreEqual(ticket.TicketType, loaded.TicketType);
        Assert.AreEqual(ticket.Priority, loaded.Priority);
        Assert.AreEqual(ticket.Summary, loaded.Summary);
        Assert.AreEqual(ticket.Background, loaded.Background);
        Assert.AreEqual(ticket.Problem, loaded.Problem);
        Assert.AreEqual(ticket.AcceptanceCriteria, loaded.AcceptanceCriteria);
        Assert.AreEqual(ticket.LinkedFilePaths, loaded.LinkedFilePaths);
        Assert.AreEqual(ticket.LinkedSymbols, loaded.LinkedSymbols);
        Assert.AreEqual(ticket.UnitTests, loaded.UnitTests);
        Assert.AreEqual(ticket.IntegrationTests, loaded.IntegrationTests);
        Assert.AreEqual(ticket.ManualTests, loaded.ManualTests);
        Assert.AreEqual(ticket.RegressionTests, loaded.RegressionTests);
        Assert.AreEqual(ticket.BuildValidation, loaded.BuildValidation);
        Assert.AreEqual(ticket.ContextSummary, loaded.ContextSummary);
        Assert.AreEqual(ticket.IsGenerated, loaded.IsGenerated);
        Assert.AreEqual(ticket.GenerationNote, loaded.GenerationNote);
    }
}
