using System;
using System.Threading;
using System.Threading.Tasks;
using IronDev.Core.Builder;
using IronDev.Core.Interfaces;

namespace IronDev.Infrastructure.Builder;

/// <summary>
/// Phase 1-3 stub implementation of IDraftTicketService.
///
/// Returns a deterministic DraftTicket derived from the supplied chat context
/// without calling the LLM. This lets the full ViewModel + UI flow be
/// developed and tested before Phase 4 wires in the real LLM.
///
/// Replacement plan (Phase 4):
///   - Inject ILLMService
///   - Build a structured prompt (similar to CodeChangeProposalService.BuildPrompt)
///   - Parse the JSON response into DraftTicket
///   - This file becomes the real implementation; the stub logic below is removed
/// </summary>
public sealed class DraftTicketService : IDraftTicketService
{
    public Task<DraftTicket> GenerateDraftAsync(
        int    projectId,
        string projectName,
        string proposedTitle,
        string messageText,
        string? linkedFilePaths,
        string? linkedSymbols,
        CancellationToken ct = default)
    {
        // Derive a short title: trim the proposed title or take the first sentence.
        var title = string.IsNullOrWhiteSpace(proposedTitle)
            ? TakeFirstSentence(messageText, maxChars: 70)
            : proposedTitle.Trim();

        // Derive a summary: first 300 chars of message text.
        var summary = messageText.Length > 300
            ? messageText[..300].TrimEnd() + "…"
            : messageText.Trim();

        var draft = new DraftTicket
        {
            Title    = title,
            TicketType = "Task",
            Priority   = "Medium",
            Status     = "Draft",
            Summary    = summary,

            Background =
                "Requirements derived from chat discussion. " +
                "Review and refine before using as a build contract.",

            AcceptanceCriteria =
                "- The feature behaves as described in the summary.\n" +
                "- Existing tests continue to pass.\n" +
                "- Build succeeds with 0 errors.",

            LinkedFilePaths = linkedFilePaths,
            LinkedSymbols   = linkedSymbols,

            // Tests — stub provides sensible defaults the developer can edit.
            UnitTests =
                $"- Verify core logic for: {title}\n" +
                "- Edge cases: null input, empty collection, boundary values.",

            IntegrationTests =
                "- End-to-end flow covering the primary use case.\n" +
                "- Verify service layer wiring is correct.",

            ManualTests =
                "- Open the relevant screen and confirm the feature works visually.\n" +
                "- Verify no UI regressions.",

            RegressionTests =
                "- All existing passing tests must still pass.\n" +
                $"- Run: dotnet test (project: {projectName})",

            BuildValidation =
                $"dotnet build {projectName}.slnx — must succeed with 0 errors, 0 warnings.",

            IsGenerated    = true,
            GenerationNote = "Generated by stub (Phase 1-3). Replace with LLM in Phase 4."
        };

        return Task.FromResult(draft);
    }

    public Task<DraftTicket> RegenerateTestsAsync(
        int         projectId,
        DraftTicket current,
        CancellationToken ct = default)
    {
        // Stub: regenerate test fields only, leave everything else unchanged.
        var updated = new DraftTicket
        {
            // Preserve all non-test fields
            SourceChatSessionId = current.SourceChatSessionId,
            SourceMessageId     = current.SourceMessageId,
            SourceMessageText   = current.SourceMessageText,
            Title               = current.Title,
            TicketType          = current.TicketType,
            Priority            = current.Priority,
            Status              = current.Status,
            Summary             = current.Summary,
            Background          = current.Background,
            AcceptanceCriteria  = current.AcceptanceCriteria,
            LinkedFilePaths     = current.LinkedFilePaths,
            LinkedSymbols       = current.LinkedSymbols,

            // Regenerated test fields (stub: append a regeneration marker)
            UnitTests =
                current.UnitTests +
                $"\n[Regenerated {DateTime.UtcNow:HH:mm:ss}] Review and refine.",

            IntegrationTests =
                current.IntegrationTests +
                $"\n[Regenerated {DateTime.UtcNow:HH:mm:ss}]",

            ManualTests      = current.ManualTests,
            RegressionTests  = current.RegressionTests,
            BuildValidation  = current.BuildValidation,

            IsGenerated    = true,
            GenerationNote = "Tests regenerated by stub. Replace with LLM in Phase 4."
        };

        return Task.FromResult(updated);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static string TakeFirstSentence(string text, int maxChars)
    {
        if (string.IsNullOrWhiteSpace(text)) return "Ticket from Chat";
        var end = text.IndexOfAny(['.', '!', '?', '\n']);
        var candidate = end > 0 ? text[..end].Trim() : text.Trim();
        return candidate.Length > maxChars
            ? candidate[..maxChars].TrimEnd() + "…"
            : candidate;
    }
}
