using System;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using IronDev.Core;
using IronDev.Core.Builder;
using IronDev.Core.Interfaces;

namespace IronDev.Infrastructure.Builder;

/// <summary>
/// Phase 4 implementation of IDraftTicketService.
/// 
/// Uses ILLMService to generate structured ticket drafts and test plans
/// based on chat context.
/// </summary>
public sealed class DraftTicketService : IDraftTicketService
{
    private readonly ILLMService _llm;

    public DraftTicketService(ILLMService llm)
    {
        _llm = llm;
    }

    public async Task<DraftTicket> GenerateDraftAsync(
        int    projectId,
        string projectName,
        string proposedTitle,
        string messageText,
        string? linkedFilePaths,
        string? linkedSymbols,
        CancellationToken ct = default)
    {
        var prompt = BuildDraftPrompt(projectName, proposedTitle, messageText, linkedFilePaths, linkedSymbols);

        string rawJson;
        try
        {
            rawJson = await _llm.GetResponseAsync(prompt);
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"AI draft generation failed: {ex.Message}", ex);
        }

        var draft = ParseDraft(rawJson);
        
        // Enrich with context-specific data not derived from LLM
        draft.LinkedFilePaths = linkedFilePaths;
        draft.LinkedSymbols   = linkedSymbols;
        draft.IsGenerated    = true;
        draft.GenerationNote = "Generated by AI.";

        return draft;
    }

    public async Task<DraftTicket> RegenerateTestsAsync(
        int         projectId,
        DraftTicket current,
        CancellationToken ct = default)
    {
        var prompt = BuildTestRegenPrompt(current);

        string rawJson;
        try
        {
            rawJson = await _llm.GetResponseAsync(prompt);
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException($"AI test regeneration failed: {ex.Message}", ex);
        }

        var testPlan = ParseTestPlan(rawJson);
        
        return new DraftTicket
        {
            SourceChatSessionId = current.SourceChatSessionId,
            SourceMessageId     = current.SourceMessageId,
            SourceMessageText   = current.SourceMessageText,
            Title               = current.Title,
            TicketType          = current.TicketType,
            Priority            = current.Priority,
            Status              = current.Status,
            Summary             = current.Summary,
            Background          = current.Background,
            AcceptanceCriteria  = current.AcceptanceCriteria,
            LinkedFilePaths     = current.LinkedFilePaths,
            LinkedSymbols       = current.LinkedSymbols,

            UnitTests        = testPlan.UnitTests ?? string.Empty,
            IntegrationTests = testPlan.IntegrationTests ?? string.Empty,
            ManualTests      = testPlan.ManualTests ?? string.Empty,
            RegressionTests  = testPlan.RegressionTests ?? string.Empty,
            BuildValidation  = testPlan.BuildValidation ?? string.Empty,

            IsGenerated    = true,
            GenerationNote = "Tests regenerated by AI."
        };
    }

    // ── Prompt Building ──────────────────────────────────────────────────────

    private static string BuildDraftPrompt(
        string projectName,
        string proposedTitle,
        string messageText,
        string? linkedFilePaths,
        string? linkedSymbols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("You are IronDev AI, a senior software architect.");
        sb.AppendLine($"Project: {projectName}");
        sb.AppendLine();
        sb.AppendLine("CONTEXT FROM CHAT:");
        sb.AppendLine($"Proposed Title: {proposedTitle}");
        sb.AppendLine($"Discussion: {messageText}");
        if (!string.IsNullOrWhiteSpace(linkedFilePaths)) sb.AppendLine($"Linked Files: {linkedFilePaths}");
        if (!string.IsNullOrWhiteSpace(linkedSymbols))   sb.AppendLine($"Linked Symbols: {linkedSymbols}");
        sb.AppendLine();
        sb.AppendLine("TASK:");
        sb.AppendLine("Convert the discussion into a high-quality, structured ticket draft.");
        sb.AppendLine("Return ONLY a JSON object. No prose. No markdown fences.");
        sb.AppendLine();
        sb.AppendLine("SCHEMA:");
        sb.AppendLine("""
            {
              "title": "Concise and descriptive title",
              "summary": "One-line executive summary",
              "background": "Requirements and technical context",
              "acceptanceCriteria": "Markdown list of criteria",
              "unitTests": "Suggested unit tests",
              "integrationTests": "Suggested integration tests",
              "manualTests": "How to verify manually",
              "regressionTests": "What to check for regressions",
              "buildValidation": "dotnet build <project>.slnx"
            }
            """);
        return sb.ToString();
    }

    private static string BuildTestRegenPrompt(DraftTicket current)
    {
        var sb = new StringBuilder();
        sb.AppendLine("You are IronDev AI, a QA engineer.");
        sb.AppendLine();
        sb.AppendLine("TICKET DETAILS:");
        sb.AppendLine($"Title: {current.Title}");
        sb.AppendLine($"Summary: {current.Summary}");
        sb.AppendLine($"Acceptance Criteria: {current.AcceptanceCriteria}");
        sb.AppendLine();
        sb.AppendLine("TASK:");
        sb.AppendLine("Generate a comprehensive test plan for this ticket.");
        sb.AppendLine("Return ONLY a JSON object matching this schema:");
        sb.AppendLine("""
            {
              "unitTests": "Markdown list",
              "integrationTests": "Markdown list",
              "manualTests": "Steps to verify",
              "regressionTests": "Potential impact areas",
              "buildValidation": "Build command"
            }
            """);
        return sb.ToString();
    }

    // ── JSON Parsing ──────────────────────────────────────────────────────────

    private static DraftTicket ParseDraft(string json)
    {
        var dto = JsonSerializer.Deserialize<DraftTicketJson>(StripFences(json), JsonOptions)
                  ?? throw new InvalidOperationException("Failed to parse ticket JSON.");

        return new DraftTicket
        {
            Title              = dto.Title              ?? "Untitled Ticket",
            Summary            = dto.Summary            ?? string.Empty,
            Background         = dto.Background         ?? string.Empty,
            AcceptanceCriteria = dto.AcceptanceCriteria ?? string.Empty,
            UnitTests          = dto.UnitTests          ?? string.Empty,
            IntegrationTests   = dto.IntegrationTests   ?? string.Empty,
            ManualTests        = dto.ManualTests        ?? string.Empty,
            RegressionTests    = dto.RegressionTests    ?? string.Empty,
            BuildValidation    = dto.BuildValidation    ?? "dotnet build"
        };
    }

    private static TestPlanJson ParseTestPlan(string json)
    {
        return JsonSerializer.Deserialize<TestPlanJson>(StripFences(json), JsonOptions)
               ?? throw new InvalidOperationException("Failed to parse test plan JSON.");
    }

    private static string StripFences(string text)
    {
        text = text.Trim();
        if (text.StartsWith("```"))
        {
            var start = text.IndexOf('\n');
            var end = text.LastIndexOf("```");
            if (start != -1 && end != -1 && end > start)
                return text.Substring(start + 1, end - start - 1).Trim();
        }
        return text;
    }

    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    private sealed class DraftTicketJson
    {
        public string? Title { get; set; }
        public string? Summary { get; set; }
        public string? Background { get; set; }
        public string? AcceptanceCriteria { get; set; }
        public string? UnitTests { get; set; }
        public string? IntegrationTests { get; set; }
        public string? ManualTests { get; set; }
        public string? RegressionTests { get; set; }
        public string? BuildValidation { get; set; }
    }

    private sealed class TestPlanJson
    {
        public string? UnitTests { get; set; }
        public string? IntegrationTests { get; set; }
        public string? ManualTests { get; set; }
        public string? RegressionTests { get; set; }
        public string? BuildValidation { get; set; }
    }
}
