import { useEffect, useMemo, useState } from 'react';
import type { TicketProposalIssueReadModel, TicketProposalReadModel } from '../../api/types';
import { CommandButton } from '../../components/CommandButton';
import type { TicketProposalController } from './useTicketProposals';

interface TicketProposalReviewPanelProps {
  controller: TicketProposalController;
  chatSessionId: number | null;
  onClose: () => void;
}

export function TicketProposalReviewPanel({
  controller,
  chatSessionId,
  onClose
}: TicketProposalReviewPanelProps) {
  const set = controller.proposalSet;
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editValue, setEditValue] = useState<TicketProposalReadModel | null>(null);
  const [regenerationInstruction, setRegenerationInstruction] = useState('');
  const [isCommitConfirmationOpen, setCommitConfirmationOpen] = useState(false);

  useEffect(() => {
    setEditingId(null);
    setEditValue(null);
    setCommitConfirmationOpen(false);
  }, [set?.revision, set?.ticketProposalSetId]);

  const orderedProposals = useMemo(
    () => [...(set?.proposals ?? [])].sort((left, right) => left.suggestedOrder - right.suggestedOrder),
    [set?.proposals]
  );
  const isCommitted = set?.status === 'Committed';
  const reviewLocked = controller.isMutating || controller.isRegenerating || controller.isCommitting ||
    controller.deliveryUnresolved || isCommitted;
  const unresolvedIssueCount = set
    ? [...set.openQuestions, ...set.potentialConflicts].filter((issue) => issue.status === 'Open').length
    : 0;

  return (
    <aside className="chat-context-panel ticket-proposal-panel" aria-label="Ticket proposal review" data-testid="chat.ticketProposals">
      <header className="chat-context-panel__header ticket-proposal-panel__header">
        <div>
          <span className="eyebrow">TICKET PROPOSALS</span>
          <h2>{isCommitted ? 'Permanent tickets created' : 'Review before tickets exist'}</h2>
          <p>{isCommitted
            ? 'The reviewed set is committed. Repository setup remains required and Builder is not authorized.'
            : 'No permanent tickets, repository files, or Builder authority are created until you explicitly confirm.'}</p>
        </div>
        <CommandButton type="button" variant="subtle" onClick={onClose} testId="chat.ticketProposals.close">
          Close
        </CommandButton>
      </header>

      {controller.loadState === 'loading' ? (
        <p className="ticket-proposal-panel__state">Loading the current proposal set...</p>
      ) : controller.loadState === 'error' ? (
        <section className="ticket-proposal-panel__state state-error" data-testid="chat.ticketProposals.error">
          <p>{controller.error}</p>
          <CommandButton type="button" variant="subtle" onClick={controller.refresh}>Retry</CommandButton>
        </section>
      ) : !set ? (
        <section className="ticket-proposal-panel__empty" data-testid="chat.ticketProposals.empty">
          <strong>No ticket proposals yet</strong>
          <p>Use <code>/ticket</code> after shaping the idea with the Business Analyst.</p>
        </section>
      ) : (
        <>
          <section className="ticket-proposal-panel__summary" data-testid="chat.ticketProposals.summary">
            <div><span>Status</span><strong>{proposalStatusLabel(set.status)}</strong></div>
            <div><span>Revision</span><strong>{set.revision}</strong></div>
            <div><span>Understanding</span><strong>{set.basedOnUnderstandingRevision}</strong></div>
            <div><span>Generated by</span><strong className="ticket-proposal-panel__mono">{shortId(set.createdByAgentRunId)}</strong></div>
          </section>

          {set.splitReason ? (
            <section className="ticket-proposal-panel__reason">
              <span>Why this split</span>
              <p>{set.splitReason}</p>
            </section>
          ) : null}

          <section className="ticket-proposal-panel__provenance" data-testid="chat.ticketProposals.sources">
            <strong>Proposal-set provenance</strong>
            <SourceMessageLinks messageIds={set.sourceMessageIds} controller={controller} />
          </section>

          {controller.deliveryUnresolved ? (
            <p className="ticket-proposal-panel__warning" data-testid="chat.ticketProposals.deliveryUnresolved">
              Delivery is unresolved. Retry only the unchanged review action.
            </p>
          ) : null}
          {controller.mutationError ? (
            <p className="state-error" data-testid="chat.ticketProposals.mutationError">{controller.mutationError}</p>
          ) : null}

          {set.status === 'NeedsInput' ? (
            <section className="ticket-proposal-panel__needs-input" data-testid="chat.ticketProposals.needsInput">
              <strong>The BA needs more project intent</strong>
              <p>No placeholder proposal was invented. Resolve the blocking question, then regenerate.</p>
            </section>
          ) : null}

          <section className="ticket-proposal-list" aria-label="Proposed tickets">
            {orderedProposals.map((proposal, index) => (
              <article
                className="ticket-proposal-card"
                key={proposal.ticketProposalId}
                data-testid={`chat.ticketProposal.${proposal.ticketProposalId}`}
              >
                {editingId === proposal.ticketProposalId && editValue ? (
                  <ProposalEditor
                    value={editValue}
                    disabled={reviewLocked}
                    onChange={setEditValue}
                    onCancel={() => { setEditingId(null); setEditValue(null); }}
                    onSave={async () => {
                      if (await controller.updateProposal(editValue)) {
                        setEditingId(null);
                        setEditValue(null);
                      }
                    }}
                  />
                ) : (
                  <>
                    <header>
                      <span className="ticket-proposal-card__order">{proposal.suggestedOrder}</span>
                      <div><h3>{proposal.title}</h3><small>{proposal.acceptanceCriteria.length} acceptance boundary item(s)</small></div>
                    </header>
                    <dl>
                      <div><dt>Problem</dt><dd>{proposal.problem}</dd></div>
                      <div><dt>Proposed change</dt><dd>{proposal.proposedChange}</dd></div>
                    </dl>
                    <section>
                      <strong>Acceptance criteria</strong>
                      <ul>{proposal.acceptanceCriteria.map((criterion, criterionIndex) => <li key={criterionIndex}>{criterion}</li>)}</ul>
                    </section>
                    {proposal.dependencyProposalIds.length > 0 ? (
                      <p className="ticket-proposal-card__dependencies">
                        Depends on {proposal.dependencyProposalIds.map(shortId).join(', ')}
                      </p>
                    ) : null}
                    <SourceMessageLinks messageIds={proposal.sourceMessageIds} controller={controller} />
                    {!isCommitted ? <footer>
                      <CommandButton
                        type="button"
                        variant="subtle"
                        disabled={reviewLocked}
                        onClick={() => { setEditingId(proposal.ticketProposalId); setEditValue(cloneProposal(proposal)); }}
                        testId={`chat.ticketProposal.${proposal.ticketProposalId}.edit`}
                      >Edit</CommandButton>
                      <CommandButton
                        type="button"
                        variant="subtle"
                        disabled={reviewLocked || index === 0}
                        onClick={() => controller.moveProposal(proposal.ticketProposalId, -1)}
                      >Move up</CommandButton>
                      <CommandButton
                        type="button"
                        variant="subtle"
                        disabled={reviewLocked || index === orderedProposals.length - 1}
                        onClick={() => controller.moveProposal(proposal.ticketProposalId, 1)}
                      >Move down</CommandButton>
                      <CommandButton
                        type="button"
                        variant="subtle"
                        disabled={reviewLocked || orderedProposals.length <= 1}
                        onClick={() => controller.removeProposal(proposal.ticketProposalId)}
                        testId={`chat.ticketProposal.${proposal.ticketProposalId}.remove`}
                      >Remove</CommandButton>
                    </footer> : null}
                  </>
                )}
              </article>
            ))}
          </section>

          <IssueGroup title="Open questions" issues={set.openQuestions} controller={controller} />
          <IssueGroup title="Potential conflicts" issues={set.potentialConflicts} controller={controller} />

          {isCommitted ? (
            <CommittedTicketSet controller={controller} />
          ) : set.status === 'Ready' ? (
            <section className="ticket-proposal-commit" data-testid="chat.ticketProposals.commit">
              <div>
                <strong>Create permanent tickets</strong>
                <p>
                  This commits all {orderedProposals.length} proposal(s) together and moves the project to Delivery.
                  It does not configure a repository or authorize Builder execution.
                </p>
              </div>
              {unresolvedIssueCount > 0 ? (
                <p className="ticket-proposal-panel__warning" data-testid="chat.ticketProposals.commit.blocked">
                  Resolve {unresolvedIssueCount} blocking question or conflict before creating tickets.
                </p>
              ) : isCommitConfirmationOpen || controller.commitDeliveryUnresolved ? (
                <div className="ticket-proposal-commit__confirmation" data-testid="chat.ticketProposals.commit.confirmation">
                  <strong>Confirm revision {set.revision}</strong>
                  <p>
                    Create {orderedProposals.length} permanent ticket(s) atomically? This records their provenance and dependency mapping.
                  </p>
                  <p className="ticket-proposal-commit__boundary">
                    Repository setup remains required. Builder is not authorized by this action.
                  </p>
                  <footer>
                    <CommandButton
                      type="button"
                      variant="subtle"
                      disabled={controller.isCommitting || controller.commitDeliveryUnresolved}
                      onClick={() => setCommitConfirmationOpen(false)}
                    >Cancel</CommandButton>
                    <CommandButton
                      type="button"
                      variant="primary"
                      disabled={controller.isCommitting || (controller.deliveryUnresolved && !controller.commitDeliveryUnresolved)}
                      onClick={() => controller.commitTickets()}
                      testId="chat.ticketProposals.commit.submit"
                    >{controller.isCommitting
                      ? 'Creating tickets'
                      : controller.commitDeliveryUnresolved
                        ? 'Retry exact ticket creation'
                        : `Confirm and create ${orderedProposals.length} ticket(s)`}</CommandButton>
                  </footer>
                </div>
              ) : (
                <CommandButton
                  type="button"
                  variant="primary"
                  disabled={reviewLocked}
                  onClick={() => setCommitConfirmationOpen(true)}
                  testId="chat.ticketProposals.commit.open"
                >Create tickets</CommandButton>
              )}
            </section>
          ) : null}

          {!isCommitted ? <section className="ticket-proposal-regenerate" data-testid="chat.ticketProposals.regenerate">
            <label htmlFor="ticket-proposal-regenerate-input">
              <strong>Regenerate this set</strong>
              <span>Give the BA an additional instruction. The current revision remains readable while it works.</span>
            </label>
            <textarea
              id="ticket-proposal-regenerate-input"
              value={regenerationInstruction}
              onChange={(event) => setRegenerationInstruction(event.target.value)}
              placeholder="For example: keep onboarding and password recovery independent."
              disabled={reviewLocked}
            />
            <CommandButton
              type="button"
              variant="primary"
              disabled={reviewLocked || !regenerationInstruction.trim() || !chatSessionId}
              onClick={async () => {
                if (await controller.regenerate(regenerationInstruction, chatSessionId)) {
                  setRegenerationInstruction('');
                }
              }}
              testId="chat.ticketProposals.regenerate.submit"
            >{controller.isRegenerating ? 'Regenerating' : 'Regenerate proposals'}</CommandButton>
          </section> : null}

          <details className="ticket-proposal-history" data-testid="chat.ticketProposals.history">
            <summary>Revision and actor history ({controller.history.length})</summary>
            <ol>
              {controller.history.map((entry) => (
                <li key={entry.revision}>
                  <details data-testid={`chat.ticketProposals.history.revision.${entry.revision}`}>
                    <summary>
                      <strong>Revision {entry.revision}</strong>
                      <span>{entry.changeKind}</span>
                    </summary>
                  <small>{entry.agentRunId
                    ? `Agent ${shortId(entry.agentRunId)} - requested by Actor ${entry.actorUserId}`
                    : `Actor ${entry.actorUserId}`}</small>
                    <RevisionSnapshot proposalSet={entry.proposalSet} controller={controller} />
                  </details>
                </li>
              ))}
            </ol>
          </details>
        </>
      )}
    </aside>
  );
}

function CommittedTicketSet({ controller }: { controller: TicketProposalController }) {
  const result = controller.commitResult;
  return (
    <section className="ticket-proposal-committed" data-testid="chat.ticketProposals.committed">
      <strong>Tickets created atomically</strong>
      {result ? (
        <>
          <p>
            {result.commitment.tickets.length} permanent ticket(s) were created from reviewed revision{' '}
            {result.commitment.reviewedRevision}. Project phase is {result.projectLifecyclePhase}; execution readiness remains{' '}
            {result.executionReadiness}.
          </p>
          {result.isReplay ? <p>The previously unresolved delivery was recovered by exact idempotent replay.</p> : null}
          <ol>
            {[...result.commitment.tickets]
              .sort((left, right) => left.suggestedOrder - right.suggestedOrder)
              .map((ticket) => (
                <li key={ticket.projectTicketId} data-testid={`chat.ticketProposals.committed.ticket.${ticket.projectTicketId}`}>
                  <a href={`/projects/${result.proposalSet.projectId}/work-items/${ticket.projectTicketId}`}>
                    Ticket #{ticket.projectTicketId}
                  </a>
                  <span>{ticket.title}</span>
                  {ticket.blockedByTicketIds.length > 0
                    ? <small>Blocked by {ticket.blockedByTicketIds.map((id) => `#${id}`).join(', ')}</small>
                    : null}
                </li>
              ))}
          </ol>
          <small className="ticket-proposal-panel__mono">Commitment {shortId(result.commitment.commitmentId)}</small>
        </>
      ) : (
        <p>This proposal set is already committed. Open the Board to inspect its permanent ticket IDs.</p>
      )}
      <p className="ticket-proposal-commit__boundary">
        Repository setup remains required. Builder is not authorized; later execution needs its own exact work-package authorization.
      </p>
    </section>
  );
}

function RevisionSnapshot({
  proposalSet,
  controller
}: {
  proposalSet: NonNullable<TicketProposalController['proposalSet']>;
  controller: TicketProposalController;
}) {
  return (
    <section className="ticket-proposal-history__snapshot">
      <p>
        <strong>{proposalStatusLabel(proposalSet.status)}</strong>
        {proposalSet.splitReason ? ` - ${proposalSet.splitReason}` : ''}
      </p>
      {proposalSet.proposals.map((proposal) => (
        <article key={proposal.ticketProposalId}>
          <h4>{proposal.suggestedOrder}. {proposal.title}</h4>
          <p><strong>Problem:</strong> {proposal.problem}</p>
          <p><strong>Proposed change:</strong> {proposal.proposedChange}</p>
          <ul>{proposal.acceptanceCriteria.map((criterion, index) => <li key={index}>{criterion}</li>)}</ul>
        </article>
      ))}
      <RevisionIssues title="Questions" issues={proposalSet.openQuestions} controller={controller} />
      <RevisionIssues title="Conflicts" issues={proposalSet.potentialConflicts} controller={controller} />
    </section>
  );
}

function RevisionIssues({
  title,
  issues,
  controller
}: {
  title: string;
  issues: TicketProposalIssueReadModel[];
  controller: TicketProposalController;
}) {
  if (issues.length === 0) {
    return null;
  }

  return (
    <section>
      <strong>{title}</strong>
      <ul>
        {issues.map((issue) => (
          <li key={issue.issueId}>
            {issue.text} - {issue.status === 'Resolved' ? issue.resolution : 'Open'}
            <SourceMessageLinks messageIds={issue.sourceMessageIds} controller={controller} />
          </li>
        ))}
      </ul>
    </section>
  );
}

function ProposalEditor({
  value,
  disabled,
  onChange,
  onCancel,
  onSave
}: {
  value: TicketProposalReadModel;
  disabled: boolean;
  onChange: (value: TicketProposalReadModel) => void;
  onCancel: () => void;
  onSave: () => void;
}) {
  return (
    <section className="ticket-proposal-editor" data-testid={`chat.ticketProposal.${value.ticketProposalId}.editor`}>
      <label>Title<input value={value.title} onChange={(event) => onChange({ ...value, title: event.target.value })} /></label>
      <label>Problem<textarea value={value.problem} onChange={(event) => onChange({ ...value, problem: event.target.value })} /></label>
      <label>Proposed change<textarea value={value.proposedChange} onChange={(event) => onChange({ ...value, proposedChange: event.target.value })} /></label>
      <label>
        Acceptance criteria
        <textarea
          value={value.acceptanceCriteria.join('\n')}
          onChange={(event) => onChange({
            ...value,
            acceptanceCriteria: event.target.value.split('\n').map((item) => item.trim()).filter(Boolean)
          })}
        />
        <small>One criterion per line.</small>
      </label>
      <footer>
        <CommandButton type="button" variant="subtle" disabled={disabled} onClick={onCancel}>Cancel</CommandButton>
        <CommandButton
          type="button"
          variant="primary"
          disabled={disabled || !proposalIsComplete(value)}
          onClick={onSave}
          testId={`chat.ticketProposal.${value.ticketProposalId}.save`}
        >Save revision</CommandButton>
      </footer>
    </section>
  );
}

function IssueGroup({
  title,
  issues,
  controller
}: {
  title: string;
  issues: TicketProposalIssueReadModel[];
  controller: TicketProposalController;
}) {
  if (issues.length === 0) {
    return null;
  }
  return (
    <section className="ticket-proposal-issues">
      <h3>{title}</h3>
      {issues.map((issue) => <IssueCard key={issue.issueId} issue={issue} controller={controller} />)}
    </section>
  );
}

function IssueCard({ issue, controller }: { issue: TicketProposalIssueReadModel; controller: TicketProposalController }) {
  const [resolution, setResolution] = useState(issue.resolution ?? '');
  return (
    <article data-testid={`chat.ticketProposal.issue.${issue.issueId}`}>
      <header><strong>{issue.kind}</strong><span>{issue.status}</span></header>
      <p>{issue.text}</p>
      <SourceMessageLinks messageIds={issue.sourceMessageIds} controller={controller} />
      {issue.status === 'Open' ? (
        <div>
          <input
            aria-label={`Resolution for ${issue.text}`}
            value={resolution}
            onChange={(event) => setResolution(event.target.value)}
            placeholder="Record the project decision"
          />
          <CommandButton
            type="button"
            variant="subtle"
            disabled={controller.isMutating || controller.isRegenerating || controller.isCommitting ||
              controller.deliveryUnresolved || controller.proposalSet?.status === 'Committed' || !resolution.trim()}
            onClick={() => controller.resolveIssue(issue.issueId, resolution)}
          >Resolve</CommandButton>
        </div>
      ) : <small>{issue.resolution}</small>}
    </article>
  );
}

function SourceMessageLinks({
  messageIds,
  controller
}: {
  messageIds: number[];
  controller: TicketProposalController;
}) {
  const [preview, setPreview] = useState<{ id: number; role: string; text: string } | null>(null);
  const [sourceError, setSourceError] = useState<string | null>(null);
  if (messageIds.length === 0) {
    return <small className="ticket-proposal-card__sources">No source messages were cited.</small>;
  }
  return (
    <div className="ticket-proposal-card__sources">
      <span>Sources</span>
      {messageIds.map((messageId) => (
        <button key={messageId} type="button" onClick={async () => {
          setSourceError(null);
          if (focusSourceMessage(messageId)) {
            setPreview(null);
            return;
          }
          try {
            const source = await controller.loadSourceMessage(messageId);
            if (!source) {
              setSourceError(`Message #${messageId} is no longer available.`);
              return;
            }
            setPreview({
              id: messageId,
              role: source.role ?? 'user',
              text: source.message ?? '(The source message has no readable text.)'
            });
          } catch {
            setSourceError(`Message #${messageId} could not be loaded.`);
          }
        }}>
          Message #{messageId}
        </button>
      ))}
      {preview ? (
        <blockquote data-testid={`chat.ticketProposals.source.${preview.id}`}>
          <strong>Message #{preview.id} ({preview.role})</strong>
          <p>{preview.text}</p>
        </blockquote>
      ) : null}
      {sourceError ? <small className="state-error">{sourceError}</small> : null}
    </div>
  );
}

function focusSourceMessage(messageId: number) {
  const target = document.querySelector<HTMLElement>(`[data-message-id="user-${messageId}"]`);
  target?.scrollIntoView({ behavior: 'smooth', block: 'center' });
  target?.focus({ preventScroll: true });
  return target !== null;
}

function cloneProposal(proposal: TicketProposalReadModel): TicketProposalReadModel {
  return {
    ...proposal,
    acceptanceCriteria: [...proposal.acceptanceCriteria],
    dependencyProposalIds: [...proposal.dependencyProposalIds],
    sourceMessageIds: [...proposal.sourceMessageIds]
  };
}

function proposalIsComplete(proposal: TicketProposalReadModel) {
  return Boolean(
    proposal.title.trim() && proposal.problem.trim() && proposal.proposedChange.trim() &&
    proposal.acceptanceCriteria.length > 0 && proposal.acceptanceCriteria.every((item) => item.trim())
  );
}

function shortId(value: string) {
  return value ? value.slice(0, 8) : 'unknown';
}

function proposalStatusLabel(status: NonNullable<TicketProposalController['proposalSet']>['status']) {
  if (status === 'Committed') return 'Committed to permanent tickets';
  return status === 'Ready' ? 'Ready for review' : 'Needs input';
}
